name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest

    - name: Build Docker image
      run: docker build -t devsecops .

    - name: Trivy security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops
        format: table
        exit-code: 0

    - name: Simulated deploy
      run: |
        echo "Despliegue simulado en entorno de preproducción"
        echo "Pipeline ejecutado correctamente"
